export const SET_USER_INFO = "SET_USER_INFO";
export const CLEAR_USER_INFO = "CLEAR_USER_INFO";

export const LOGIN_HANDLER = "LOGIN_HANDLER";
export const LOGIN_HANDLER_SUCCESS = "LOGIN_HANDLER_SUCCESS";
export const LOGIN_HANDLER_FAILED = "LOGIN_HANDLER_FAILED";

export const REGISTER_HANDLER = "REGISTER_HANDLER";
export const REGISTER_HANDLER_SUCCESS = "REGISTER_HANDLER_SUCCESS";
export const REGISTER_HANDLER_FAILED = "REGISTER_HANDLER_FAILED";
