export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const SET_USER_INFO = "SET_USER_INFO";
export const CLEAR_USER_INFO = "CLEAR_USER_INFO";

export const LOGIN_HANDLER_REQUEST = "LOGIN_HANDLER_REQUEST";
export const LOGIN_HANDLER_SUCCESS = "LOGIN_HANDLER_SUCCESS";
export const LOGIN_HANDLER_FAILED = "LOGIN_HANDLER_FAILED";

export const REGISTER_HANDLER_REQUEST = "REGISTER_HANDLER_REQUEST";
export const REGISTER_HANDLER_SUCCESS = "REGISTER_HANDLER_SUCCESS";
export const REGISTER_HANDLER_FAILED = "REGISTER_HANDLER_FAILED";
