export const ConstantsEnum = {
  SET_USER_INFO: "SET_USER_INFO",
  CLEAR_USER_INFO: "CLEAR_USER_INFO",
  ADD_NEW_OFFER: "ADD_NEW_OFFER",
  SET_ACTIVE_OFFER: "SET_ACTIVE_OFFER",
  GET_JOBS_OFFERS: "GET_JOBS_OFFERS"
};
