export const GET_JOBS_OFFERS_REQUEST = "GET_JOBS_OFFERS_REQUEST";
export const GET_JOBS_OFFERS_SUCCEEDED = "GET_JOBS_OFFERS_SUCCEEDED";
export const GET_JOBS_OFFERS_FAILED = "GET_JOBS_OFFERS_FAILED";

export const ADD_NEW_OFFER_REQUEST = "ADD_NEW_OFFER_REQUEST";
export const ADD_NEW_OFFER_SUCCEDED = "ADD_NEW_OFFER_SUCCEDED";
export const ADD_NEW_OFFER_FAILED = "ADD_NEW_OFFER_FAILED";

export const GET_PRIVATE_JOBS_REQUEST = "GET_PRIVATE_JOBS_REQUEST";
export const GET_PRIVATE_JOBS_SUCCEDED = "GET_PRIVATE_JOBS_SUCCEDED";
export const GET_PRIVATE_JOBS_FAILED = "GET_PRIVATE_JOBS_FAILED";

export const DELETE_OFFER_REQUEST = "DELETE_OFFER_REQUEST";
export const DELETE_OFFER_SUCCEDED = "DELETE_OFFER_SUCCEDED";
export const DELETE_OFFER_FAILED = "DELETE_OFFER_FAILED";

export const SET_OFFER_FILTER_CITY = "SET_OFFER_FILTER_CITY";
export const SET_OFFER_FILTER_SPEC = "SET_OFFER_FILTER_SPEC";
export const SET_OFFER_FILTER_TECH = "SET_OFFER_FILTER_TECH";

export const SET_ACTIVE_OFFER = "SET_ACTIVE_OFFER";
