export const GET_JOBS_OFFERS = "GET_JOBS_OFFERS";
export const GET_JOBS_OFFERS_SUCCEEDED = "GET_JOBS_OFFERS_SUCCEEDED";
export const GET_JOBS_OFFERS_FAILED = "GET_JOBS_OFFERS_FAILED";

export const ADD_NEW_OFFER = "ADD_NEW_OFFER";
export const ADD_NEW_OFFER_SUCCEDED = "ADD_NEW_OFFER_SUCCEDED";
export const ADD_NEW_OFFER_FAILED = "ADD_NEW_OFFER_FAILED";

export const SET_ACTIVE_OFFER = "SET_ACTIVE_OFFER";
